# Terza probabile implementazione di PNN ☣
https://github.com/antoniogrv/probabilistic-neural-network - *link di riferimento*

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored

# **Import librerie**

In [ ]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score  # importa alcune funzioni di valutazione delle prestazioni del modello
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale

# Caricamento dataset iris con suddivisione in training set e test set


In [ ]:
# Definisce una funzione denominata "input()" che non riceve argomenti in ingresso
def input():
    # Carica i dati del dataset Iris utilizzando il metodo "load_iris()" del modulo "datasets" di scikit-learn
    iris = datasets.load_iris()
    # Assegna le caratteristiche ai dati contenuti nella variabile "x"
    x = iris.data
    # Assegna le etichette ai dati contenuti nella variabile "y"
    y = iris.target
    
    # Scala le caratteristiche del dataset "x" utilizzando la funzione "scale()" del modulo "preprocessing" di scikit-learn
    x = scale(x)
    
    # Utilizza la funzione "train_test_split()" del modulo "model_selection" di scikit-learn per dividere il dataset in un set di training e un set di test
    # Imposta una proporzione del 70% di dati per il training set e del 30% di dati per il test set
    # Imposta un valore di "random_state" a 0 per garantire la riproducibilità dei risultati
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)
    
    # Crea un dizionario "data" contenente i quattro array di dati risultanti dalla suddivisione del dataset
    data = {'x_train': x_train, 
            'x_test': x_test, 
            'y_train': y_train, 
            'y_test': y_test}
    
    
    # Restituisce il dizionario "data" come risultato della funzione "input()"
    return data



# Caricamento datasets BABELE


*   Training set
*   Validation set
*   Test set




## Caricamento Training set BABELE




In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Biometria/CSV_DATASET/Train_babele_cityblock.csv')

# Rimuove le colonna "target" e "video-frame" dal dataset e assegna i dati rimanenti alla matrice delle features X
X_train = df_train.drop(columns=['target', 'video-frame'], axis=1); #TRAIN X
print(50*"-"+"X_TRAIN"+"-"*50)
print(X_train)

# Seleziona la colonna "target" e assegna i dati all'array delle etichette Y
Y_train = df_train[['target']] #TRAIN Y
print(50*"-"+"Y_TRAIN"+"-"*50)
print(Y_train)

## Caricamento Validation set BABELE


In [ ]:
df_validation = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Biometria/CSV_DATASET/Validation.csv')

# Rimuove le colonna "target" e "video-frame" dal dataset e assegna i dati rimanenti alla matrice delle features X
X_validation = df_validation.drop(columns=['target', 'video-frame'], axis=1); #TRAIN X
print(50*"-"+"X_VALIDATION"+"-"*50)
print(X_validation)

# Seleziona la colonna "target" e assegna i dati all'array delle etichette Y
Y_validation = df_validation[['target']] 
print(50*"-"+"Y_VALIDATION"+"-"*50)
print(Y_validation)





--------------------------------------------------X_VALIDATION--------------------------------------------------
         37-267     61-306     84-314      37-84       0-17    267-314
0      0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
1      9.000000  27.018512   8.000000  15.132746  15.132746  15.033296
2      8.000000  26.019224   8.000000  11.000000  10.000000  11.000000
3      8.000000  25.000000   8.062258  13.000000  12.000000  12.000000
4      7.000000  24.000000   8.000000  13.000000  13.000000  13.038405
...         ...        ...        ...        ...        ...        ...
1595  10.440307  30.805844   9.219544  14.317821  14.560220  13.601471
1596  10.198039  32.984845   9.219544  12.369317  13.601471  12.649111
1597   9.055385  31.400637  10.198039  15.297059  16.278821  16.124515
1598  10.198039  31.575307  10.198039  15.132746  16.124515  15.132746
1599  13.038405  42.426407  13.152946  21.213203  22.203603  22.203603

[1600 rows x 6 columns]
----------

## Caricamento Test set BABELE

In [ ]:
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Biometria/CSV_DATASET/Test_babele_cityblock.csv')

# Rimuove la colonna "target" dal dataset e assegna i dati rimanenti alla matrice delle features X
X_test = df_test.drop(columns=['target', 'video-frame'], axis=1); #TRAIN X
print(50*"-"+"X_TEST"+"-"*50)
print(X_test)

# Seleziona la colonna "target" e assegna i dati all'array delle etichette Y
Y_test = df_test[['target']] #TRAIN Y
print(Y_test)

--------------------------------------------------X_TEST--------------------------------------------------
     37-267_0  61-306_0  84-314_0   37-84_0    0-17_0  267-314_0  37-267_1  \
0    0.027979  0.091484  0.027880  0.047988  0.047445   0.048191  0.021962   
1    0.015919  0.053563  0.015976  0.038931  0.038009   0.038874  0.018831   
2    0.017207  0.053732  0.019266  0.069050  0.070789   0.071110  0.023425   
3    0.019881  0.061997  0.020145  0.047103  0.046868   0.047540  0.018061   
4    0.017456  0.057951  0.017618  0.039854  0.039597   0.040044  0.015534   
..        ...       ...       ...       ...       ...        ...       ...   
155  0.016625  0.057409  0.016617  0.036661  0.036249   0.036652  0.014969   
156  0.015001  0.048505  0.015162  0.036214  0.036365   0.036392  0.011436   
157  0.015019  0.048462  0.015710  0.046680  0.046549   0.045075  0.014538   
158  0.012699  0.040637  0.013195  0.029949  0.029456   0.029610  0.012480   
159  0.010600  0.033786  0.012753  

# Implementazione dell'algoritmo di classificazione PNN

In [ ]:
# Funzione di base radiale utilizzata nella PNN
def rbf(centre, x, sigma):  
    centre = centre.reshape(1, -1)  # riformatta il centro in un array 1D
    temp = -np.sum((centre - x) ** 2, axis=1)  # calcola la distanza quadratica tra il centro e i punti di dati
    temp = temp / (2 * sigma * sigma)  # applica il parametro di larghezza di banda
    temp = np.exp(temp)  # applica la funzione esponenziale
    gaussian = np.sum(temp)  # somma i valori calcolati
    return gaussian  # restituisce il valore finale

def subset_by_class(data, labels):  # funzione per creare sottoinsiemi di dati per classe
    x_train_subsets = []  # lista vuota per i sottoinsiemi di dati
    for l in labels:  # per ogni classe di etichette
        indices = np.where(data['y_train'] == l)  # seleziona gli indici dei punti di dati che appartengono alla classe corrente
        x_train_subsets.append(data['x_train'][indices, :])  # aggiungi i punti di dati nella lista di sottoinsiemi
    return x_train_subsets  # restituisci la lista di sottoinsiemi di dati per ciascuna classe

def PNN(data, sigma):  # funzione per l'algoritmo di classificazione PNN
    num_testset = data['x_test'].shape[0]  # numero di punti di dati nel set di test
    labels = np.unique(data['y_train'])  # etichette uniche nel set di training
    num_class = len(labels)  # numero di classi
    print("Numero di classi riscontrato: ", num_class)
    sigma = sigma  # parametro di larghezza di banda
    x_train_subsets = subset_by_class(data, labels)  # crea sottoinsiemi di dati per ciascuna classe
    summation_layer = np.zeros(num_class)  # inizializza il vettore per la somma dei valori di ciascuna classe
    predictions = np.zeros(num_testset)  # inizializza il vettore per le etichette di classificazione predette
    for i, test_point in enumerate(data['x_test']):  # per ogni punto di dati nel set di test
        for j, subset in enumerate(x_train_subsets):  # per ogni sottoinsieme di dati di ogni classe
            summation_layer[j] = np.sum(rbf(test_point, subset[0], sigma)) / subset[0].shape[0]  # calcola la somma dei valori di ciascuna classe
        predictions[i] = np.argmax(summation_layer)  # assegna all'etichetta predetta la classe corrispondente al valore massimo del vettore di somma
    return predictions  # restituisce le etichette di classificazione predette per il set di test

def print_metrics(y_test, predictions):  # funzione per stampare le metriche di valutazione delle prestazioni del modello
    print('Confusion Matrix')
    print(confusion_matrix(y_test, predictions))  # stampa la matrice di confusione
    print('Accuracy: {}'.format(accuracy_score(y_test, predictions)))  # stampa l'accuratezza
    print('Precision: {}'.format(precision_score(y_test, predictions, average='micro')))  # stampa la precisione
    print('Recall: {}'.format(recall_score(y_test, predictions, average='micro')))  # stampa il richiamo




# Predizione su singolo input

La funzione predict_PNN prende in input un singolo fiore rappresentato da un array random_flower, che viene passato alla funzione PNN per effettuare la classificazione dei dati di input. In particolare, l'array random_flower viene convertito in un array 2D x_test contenente una singola riga, che viene utilizzato come input per la funzione PNN.

Quindi, la funzione predict_PNN è progettata per effettuare la predizione della classe di un singolo fiore. Se si desidera effettuare la predizione di più fiori contemporaneamente, è possibile modificare la funzione predict_PNN per accettare un array di fiori come input e chiamare la funzione PNN con l'intero array di dati di input.

In [ ]:
# Funzione per la predizione dei dati di input
def predict_PNN(random_flower, data):
    # crea un dizionario contenente i dati di input e le etichette di classe corrispondenti
    data = {
        'x_test': np.array([random_flower]),  # converte i dati di input in un array 2D
        'y_test': np.array([0]),  # assegna un'etichetta di classe fittizia, che verrà sovrascritta dalla funzione PNN
        'y_train': data['y_train'],  # array 1D con le etichette di classe del set di training
        'x_train': data['x_train']  # array 2D con i valori di input del set di training
    }

    # chiama la funzione PNN per effettuare la classificazione dei dati di input
    predicted_class = PNN(data)

    return predicted_class

# Esecuzione su test set di Babele


In [ ]:
# acquisisce i dati di input, prende i test set
#data = input()
data = {'x_train': X_train.values, 
            'x_test': X_test.values, 
            'y_train': Y_train.values, 
            'y_test': Y_test.values}

sigma = 0.30 #Scelgo il sigma 0.30

predictions = PNN(data, sigma)  # chiama la funzione PNN per effettuare la classificazione dei dati di input
print(predictions)  # stampa le etichette di classificazione predette per i dati di input
print_metrics(data['y_test'], predictions)  

Numero di classi riscontrato:  8
[4. 4. 4. 4. 4. 4. 7. 4. 7. 7. 4. 4. 4. 4. 4. 1. 1. 1. 1. 1. 2. 2. 2. 2.
 2. 4. 4. 4. 7. 7. 4. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 7. 7. 7.
 7. 7. 4. 5. 7. 7. 7. 7. 7. 7. 7. 7. 5. 5. 5. 5. 5. 7. 7. 7. 7. 7. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 7. 4. 4. 4. 4. 2. 2. 2. 2. 4. 2. 2. 2. 1. 2. 2.
 1. 1. 2. 1. 2. 2. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 4. 2. 2. 4. 2. 2. 4. 4.
 4. 4. 7. 7. 5. 5. 4. 7. 4. 7. 7. 7. 7. 5. 7. 2. 2. 2. 2. 1. 7. 7. 7. 7.
 7. 4. 4. 4. 4. 2. 7. 7. 7. 7. 7. 5. 5. 5. 5. 5.]
Confusion Matrix
[[ 5  0  0 12  0  0  3  0]
 [ 2 12  0  5  0  0  1  0]
 [ 5 15  0  0  0  0  0  0]
 [ 0  6  0 12  0  0  2  0]
 [ 0  0  0  6  1  0 13  0]
 [ 0  0  0  0 15  0  5  0]
 [ 0  1  0  8  3  0  8  0]
 [ 0  1  0  4  5  0 10  0]]
Accuracy: 0.2375
Precision: 0.2375
Recall: 0.2375


# Esecuzione su Random Flower

esegue la predizione della classe di un singolo fiore rappresentato dall'array random_flower e capire se dà lo stesso output delle altre considerate

In [ ]:
# Esegui la predizione sui dati di input
random_flower = np.array([3.1, 4.5, 5.2, 2.1])  # definisce i dati di input
predicted_class = predict_PNN(random_flower, data)

print("Dati del fiore in input: ", random_flower)
# stampa la classe predetta
print("Classe predetta:", predicted_class)

Dati del fiore in input:  [3.1 4.5 5.2 2.1]
Classe predetta: [2.]
